language: node_js
install: npm install
before_script: npm run build
script: npm test
os:
  - linux
  - osx
node_js:
  - "10"
  - "9"
  - "8"
branches:
  only:
    - master
notifications:
  email:
    - tucchun@hotmail.com