language: node_js
install: npm install
before_script: npm run build
script: npm test
os:
  - inux
  - osx
node_js:
  - "8"
  - "7"
  - "6"
branches:
  only:
    - master
notifications:
  email:
    - tucchun@hotmail.com